// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cm.adorsys.gpao.model;

import cm.adorsys.gpao.model.GpaoBaseEntity;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect GpaoBaseEntity_Roo_Configurable {
    
    declare @type: GpaoBaseEntity: @Configurable;
    
}
