// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cm.adorsys.gpao.model;

import cm.adorsys.gpao.model.OrderItems;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect OrderItems_Roo_Configurable {
    
    declare @type: OrderItems: @Configurable;
    
}
