package cm.adorsys.gpao.model;


public enum RoleNames {

    ROLE__MODULE_ADMINISTRATION , ROLE_ACCESS_UDM,ROLE_ACCESS_TAXE,ROLE_ACCESS_FAMILLE_PRODUIT,ROLE_ACCESS_MONNAIE,ROLE_ACCESS_EMPLACEMENT
    ,ROLE_ACCESS_COMPANY,ROLE_ACCESS_UTILISATEUR,ROLE_ACCESS_GROUPE_UTILISATEUR
    
    ,ROLE_MODULE_ACHAT,ROLE_ACCESS_FOURNISSEUR,ROLE_ACCESS_CLIENT,ROLE_ACCESS_GROUPE_PARTENAIRE,ROLE_ACCESS_BON_COMANDE,ROLE_ACCESS_APPEL_OFFRE,
    ROLE_ACCESS_PRODUIT ,ROLE_ACCESS_LIVRAISON,
   
    ROLE_MODULE_STOCK,ROLE_ACCESS_INVENTAIRE,ROLE_ACCESS_MOUVEMENT_STOCK,
    
    ROLE_MODULE_PRODUCTION, ROLE_ACCESS_COMMANDE_CLIENTS,ROLE_ACCESS_BON_PRODUCTION,ROLE_ACCESS_BON_PRODUCTION_MATIEREPREMIERE,
    ROLE_ACCESS_CONTROLE_PRODUCTION;
}
